### ISSUE TITLE
error after install

### ISSUE THREAD

**Issue by awrog** [francodacosta/grav-plugin-page-stats#1]
This plugin looks promising!!

After installing the plugin the menu item 'Page Stats' displays

![Screenshot - 8_1_2022 , 1_03_13 PM](https://user-images.githubusercontent.com/12153667/182134780-faf70c1f-7eb6-4324-870c-d5eab1640a38.png)

..../public_html/user/plugins/page-stats/data contains a zip-file: geolocation.sqlite.zip, no sqlite db-file
To investigate I manually extracted 'geolocation.sqlite'

Still no page when I click the menu item.

The plugin **is** collecting data in user/data/page-data.sqlite

Turning the plugin 'off' and 'on' again does not solve the problem.

**Comment by francodacosta** [comment]
thanks, I will look into it this eveningif you have the zip extension the file should be extracted automatically on first runmake sure you go to plug-in settings and hit save, as sometimes the plugin does not get the settings if they are not saved onceif you go to tool and then logs you should have more info toonunoOn 1 Aug 2022 12:50, awrog ***@***.***> wrote:
I could not help noticing this typo

**Comment by awrog** [comment]
Hi Franco, Thanks for you swift reply.
I've re-installed and saved the plugin settings page.
/public_html/user/config/plugins contains the file page-stats.yaml with content:
```
enabled: true
db: user/data/page-data.sqlite
log_admin: false
log_bot: false
```
Log attached:
[page-stat-log.zip](https://github.com/francodacosta/grav-plugin-page-stats/files/9233821/page-stat-log.zip)

**Comment by francodacosta** [comment]
there might be a typo, try adding `log_bots: false` to the config please

**Comment by awrog** [comment]
Franco, adding `log_bots: false` helped to prevent the errors in the log.

The page-stats 404-error is still there.

Advice:
I would store the data in `.../user/data/page-data/page-data.sqlite`
 instead of
`.../user/data/page-data.sqlite`
That's more clear/manageable :-)

**Comment by francodacosta** [comment]
what is the URL that is giving you the 404? I've never got that beforeNunoOn 1 Aug 2022 14:24, awrog ***@***.***> wrote:
Franco, adding log_bots: false helped to prevent the errors in the log.
The page-stats 404-error is still there.
Advice:
I would store the data in .../user/data/page-data/page-data.sqlite
instead of
.../user/data/page-data.sqlite
That's more clear/manageable :-)

**Comment by francodacosta** [comment]
@awrog what version of grav and admin plugin are you using ?

I'm on Grav v1.7.34 - Admin v1.10.34

**Comment by awrog** [comment]
Franco, both the latest. (1.7.34, 1.10.34)
Hosting is on a shared server.
The url is: [domain]/[adminaccount]/page-stats  (I only have ftp-access to
this environment tomorrow morning (eu timezone)).

**Comment by francodacosta** [comment]
is the admin route not `/admin` ?

**Comment by awrog** [comment]
Franco,

No, due to security-reasons it is advised to change it to something
different then /admin !

This can be changed in the admin plugin.

I appreciate the help!

**Comment by francodacosta** [comment]
That's the problem!

I'm working on a fix now

**Comment by awrog** [comment]
Great!

**Comment by francodacosta** [comment]
@awrog can you try out https://github.com/francodacosta/grav-plugin-page-stats/releases/tag/0.1.2 

should be fixed

**Comment by awrog** [comment]
Great many thanks.
I'll install it asap and I will let you know!

**Comment by awrog** [comment]
The 'Page Stats' menu-entry works!
