### ISSUE TITLE
Wrong links to github/homepage of the plugin

### ISSUE THREAD

**Issue by awrog** [francodacosta/grav-plugin-page-stats#2]
No biggie, the links to the github repo in the plugin are wrong

![Screenshot - 8_2_2022 , 9_39_27 AM](https://user-images.githubusercontent.com/12153667/182319684-f919e76d-e4ff-4224-849c-cf8c543ce475.png)

**Comment by francodacosta** [comment]
it is indeed. 1.0.3 should fix it
