### ISSUE TITLE
Platform and browser switched in stats page.

### ISSUE THREAD

**Issue by yurigiu** [francodacosta/grav-plugin-page-stats#22]
As title, platform and browser are switched in stats page ("Platform" column shows browsers and "Browser" column shows platforms).
In both "Recently viewed pages" widget in the dashboard and "Page Details" page.

Please see screenshot:

![image](https://user-images.githubusercontent.com/60064799/187038373-767742c3-0225-4154-ac15-49484110bea4.png)

**Comment by francodacosta** [comment]
hi @yurigiu thanks for reporting the  errors.

They should all be fixed in 2.1.0

Let me know of you experience using the plugin, I build it for myself, so i'm not very sure of what other people find useful or not

**Comment by yurigiu** [comment]
I like it, I am using it for some days now.
If you are looking for some suggestions, I would say the following:
- To make it **really** useful, it needs some analysis of the referrals (eg. from which original sites the users are coming from). With this, the plugin could even replace a full-blown analytics service, for small sites.
- A way to reset the statistics, maybe a button in the configuration page?

**Comment by francodacosta** [comment]
@yurigiu thanks

Latest version is aready collecting referal data but not diplaying it yet
