### ISSUE TITLE
Request: filter for requests to ignore

### ISSUE THREAD

**Issue by anders8** [francodacosta/grav-plugin-page-stats#23]
Would love to be able to ignore any requests for wlwmanifest.xml since the bots are searching every IP in existence for it. I'm sure in 6 months it'll be some other WP vulnerability.

I suppose a regex to add a list of terms to ignore in the display would be the fix there: still _record_ it, just don't include it in stats/calcs.

👍👍

**Comment by francodacosta** [comment]
@anders8 I'm facing the same problem it;s wlwmanifest.xml` and `wp-login.php`

I will look into that

**Comment by francodacosta** [comment]
@anders8 can you try [2.2.0](https://github.com/francodacosta/grav-plugin-page-stats/releases/tag/2.2.0)

should add the filter by url and a bunch of new featires and bug fixes

**Comment by anders8** [comment]
Is the filtering happening on the recording (front end) or on the stats display(back end)? In other words, the junk I have in there already, does it _stay_ in, even applying the new filters?

(unrelated, the new circle graphs are nice. 👍)

**Comment by francodacosta** [comment]
@anders8 glad you like the pie charts, you can switch back to the table charts in the config if you want to

Unfortunately the filtering  happens at write time (so on the back end) so the junk will stay in

It is fairly easy to delete it manually if you want, all the data is in a single table
