### ISSUE TITLE
Feature Request: show URL instead of page name

### ISSUE THREAD

**Issue by anders8** [francodacosta/grav-plugin-page-stats#27]
In "recently viewed" and "most viewed", have the option of showing the url instead of (or in addition to) the page name. Minus the base URL, naturally. Currently, there's no way to see if I've loaded a page with a tracker like /page.html/?qrcode=1 as it will have the same page name.

This will make the text field longer... at least for "full width" it would look much better if the viewed columns did not all have the same weight. (25% 25% 25% 25%) but rather something like 55% 15% 15% 15%.

Thanks man, great work on the updates recently.

**Comment by francodacosta** [comment]
it's on https://github.com/francodacosta/grav-plugin-page-stats/releases/tag/2.4.0
