### ISSUE TITLE
Req: exclude page and ip address

### ISSUE THREAD

**Issue by awrog** [francodacosta/grav-plugin-page-stats#3]
The plugin works really well and is definitely an alternative to Google analytics.

It would add great value:
* if I could exclude a page or pages (via frontmatter)
* if I could exclude my own ip address

**Comment by francodacosta** [comment]
@awrog so yu want a front matter setting to not process a page ?

and a list of ips to exclude from analytics ?

**Comment by awrog** [comment]
@francodacosta That would be great.

An example for the frontmatter:
```
page-stats:
    process: false
```

A list of ip's to exclude in the plugin page would be awsome.

**Comment by francodacosta** [comment]
@awrog I agree it would be useful, I will implement that

another thing i'm considering is to block for a certain time IP's that constantly hit 404 pages. like '/wp-login.php'

**Comment by awrog** [comment]
Nice, mostly bots hoping it's WordPress ;-)
Excluding 404 / errorpage would be a nice addition (and also, there are other tools to check dead links)

**Comment by awrog** [comment]
Clickable pagetitles would also be nice (convert title attribute to href)

**Comment by francodacosta** [comment]
@awrog can you look at https://github.com/francodacosta/grav-plugin-page-stats/releases/tag/1.1.0 ?

should allow to exclude ips (either by ip or regular expression) and exclude pages via front matter

**Comment by awrog** [comment]
@francodacosta  Simply brilliant! Also the feature to hide the unique visitors (I removed them myself ;-) )
I also changed the number of rows that are being displayed ($limit = 10 => 20)
Would be nice if I could specify that too in the plugin page. (no biggie, juist a 'nice to have')
All in all, great additions!

**Comment by francodacosta** [comment]
@awrog have a look at `1.2.0`

I added the hability to:
 * enable/disable each widget 
 * configure how many columns each widget uses in the grid
 * records to fetch for top pages, most viewed pages and top users

**Comment by awrog** [comment]
@francodacosta Impressive, really perfect.
The only thing I customize, is  
<span title="{{s.route}}"><a href="{{s.route}}">{{s.page_title}}</a></span>
I have a lot of pages with the same title, (and quite an extensive side menu (https://github.com/hibbitts-design/grav-theme-learn2-git-sync) )

Keep up the good work!!

**Comment by francodacosta** [comment]
@awrog you want the url instea of the title ?

**Comment by francodacosta** [comment]
@awrog have a look at 1.3.1

this version needs a db migration as it collects browser and os info
it should happen automatically, if not make sure you have an emplty file on `<plugin folder>/data/migrations/MUST_MIGRATE`

**Comment by awrog** [comment]
> @awrog you want the url instead of the title ?

A clickable title would be fine
I see Github interpreted by code, I meant:

```twig
<span title="{{s.route}}"><a href="{{s.route}}">{{s.page_title}}</a></span>
```
![image](https://user-images.githubusercontent.com/12153667/183076110-77494bf4-5dbf-44f6-a522-d8e77d3c91c2.png)

**Comment by francodacosta** [comment]
@awrog I might put a link (icon) to take you to the page.

My plan for when you click the page, is to go to a detailed stats page for that page

**Comment by awrog** [comment]
> @awrog I might put a link (icon) to take you to the page.
> 
> My plan for when you click the page, is to go to a detailed stats page for that page

Nice, the url is awkward since it can be long (sometimes very long)
Title is just fine

![image](https://user-images.githubusercontent.com/12153667/183077478-b769bc7c-cad8-4943-81c5-6e2ec7accdb2.png)

=> In the plugin page, a title is missing

![image](https://user-images.githubusercontent.com/12153667/183077646-a544e6dd-c99d-4a7b-a811-a9a5459c1507.png)

**Comment by awrog** [comment]
v1.5.0 all perfect now!

**Comment by awrog** [comment]
@francodacosta You've been busy I see ;-)
The page details are awsome!

The fact that you have to click on the pagename is not very intuitive for such a great feature.
Might I suggest a swap:
 - click on the pagename = open the page
 - click on the icon left from the pagename (e.g. fa-solid fa-chart-line or fa-solid fa-chart-column) opens the details page
 
 Just my two cents...
