### ISSUE TITLE
Feature Request: Configure Ignored Bots

### ISSUE THREAD

**Issue by Freddicus** [francodacosta/grav-plugin-page-stats#30]
Your Readme says
 
> Bot detection is based on user agent, it is not perfect, but it does work well

I would like to be able to configure this. For example, I have UpTimeRobot pinging my website, and I'd like to filter it out.

Workaround: IP filtering (but I don't know if their IP is static)

> User Agent: Mozilla/5.0+(compatible; UptimeRobot/2.0; http://www.uptimerobot.com/)

**Comment by francodacosta** [comment]
@Freddicus sure, I guess I can make the bot filtering rules configurable

**Comment by francodacosta** [comment]
@Freddicus can you please test [2.5.0](https://github.com/francodacosta/grav-plugin-page-stats/releases/tag/2.5.0) ?

**Comment by Freddicus** [comment]
Confirmed! Thanks!
